Python 2.7 AMD CPU:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=amd:pu
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - amd-cl-cpu
  except:
  - tags
Python 3.4 AMD CPU:
  script:
  - export PY_EXE=python3.4
  - export PYOPENCL_TEST=amd:pu
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.4
  - amd-cl-cpu
  except:
  - tags
Python 2.6 AMD CPU:
  script:
  - export PY_EXE=python2.6
  - export PYOPENCL_TEST=amd:pu
  - EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.6
  - amd-cl-cpu
  except:
  - tags
  - cffi  # triggers a bug that I'm not feeling like debugging
Python 2.7 K20:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=nvi:k20
  - exprot EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - cuda
  except:
  - tags
PyPy AMD CPU:
  script:
  - export PY_EXE=pypy
  - export PYOPENCL_TEST=amd:pu
  - exprot EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - pypy
  except:
  - tags
  - master
