"Python 2.7 AMD CPU (+GL and special func)":
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=amd:pu
  - export EXTRA_INSTALL="numpy mako scipy pyfmmlib"
  - echo "CL_ENABLE_GL = True" > siteconf.py
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - amd-cl-cpu
  - opengl
  except:
  - tags
Python 2.7 Intel CPU:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST="intel(r):pu"
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - intel-cl-cpu
  except:
  - tags
  - master
Python 3.4 AMD CPU:
  script:
  - export PY_EXE=python3.4
  - export PYOPENCL_TEST=amd:pu
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.4
  - amd-cl-cpu
  except:
  - tags
Python 2.6 AMD CPU:
  script:
  - export PY_EXE=python2.6
  - export PYOPENCL_TEST=amd:pu
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.6
  - amd-cl-cpu
  except:
  - tags
Python 2.7 C2070:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=nvi:c20
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - cuda
  except:
  - tags
Python 2.7 POCL:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - pocl
  except:
  - tags
Python 2.7 Apple:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=app:cpu
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - apple
  except:
  - tags
PyPy POCL:
  script:
  - export PY_EXE=pypy
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - pypy
  - pocl
  except:
  - tags
