jobs:
-
    job: 'Pytest'
    pool:
        vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

    steps:
    -
        task: UsePythonVersion@0
        inputs:
            versionSpec: '$(python.version)'

    -
        script: |
            set -e
            CONDA_ENVIRONMENT=.test-conda-env-py3.yml
            curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project-within-miniconda.sh
            ". ./build-and-test-py-project-within-miniconda.sh"

        displayName: 'Pytest Conda'

-
    job: 'Flake8'
    pool:
        vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'
    strategy:
        matrix:
            Python36:
                python.version: '3.6'

    steps:
    -
        task: UsePythonVersion@0
        inputs:
            versionSpec: '$(python.version)'

    -
        script: |
            set -e
            curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
            . ./prepare-and-run-flake8.sh pyopencl test

        displayName: 'Flake8'
